name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v19
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: Build derani
        run: nix build .#derani -o derani
      - name: Build latin
        run: nix build .#latin -o latin
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: latest
          prerelease: false
          files: '{derani,latin}-fonts/share/fonts/*/*'
